### ISSUE TITLE
Add workflow to build the documentation 

### ISSUE THREAD

**Issue by opeolluwa** [opeolluwa/racoon#136]
Add an [mdbook](https://rust-lang.github.io/mdBook/) workflow to build the project documentation.  

The documentation should be built and pushed to the `gh-pages branch` of the repository once the updates are merged (or pushed) into the `production branch`.

**Comment by opeolluwa** [comment]
A workflow already exists for this but, the workflow builds the documentation, and the output doesn't include `index.html` in the root directory

**Comment by opeolluwa** [comment]
The application page still returns a 404 error. 

I think this is due to index.html file not included in the built source found in the `gh-pages` branch.  

Could you please review this

**Comment by Karthik-d-k** [comment]
This is strange, when i build locally, `index.html` is present in `docs/book` folder.
It is getting deleted in the `gh-pages` branch.
I will try to debug this again.

**Comment by opeolluwa** [comment]
I had a similar experience too,  it all works fine on my machine

**Comment by Karthik-d-k** [comment]
Hey,

I finally found out the issue while playing with the commands locally..
`index.html` file is ignored because it is present in root `.gitignore` file -->
```
#ignore binary files in the sandbox
sandbox/*
!sandbox/*.rs
sandbox/calendar.html
/*.html
```
I don't have enough knowledge about the project structure, so you can decide on keeping/deleting this from .gitignore.

**Comment by opeolluwa** [comment]
Well done @Karthik-d-k

**Comment by Karthik-d-k** [comment]
Finally we did it 🚀

**Comment by opeolluwa** [comment]
You are the best, man! ❤️
I love the resilience

**Comment by opeolluwa** [comment]
Could you please make the final PR on this tough guy 😄

**Comment by Karthik-d-k** [comment]
shall i remove inspect code in mdbook.yml file, bcz we dont want it anyway ?

**Comment by opeolluwa** [comment]
No, it's all good.  You can leave
