### ISSUE TITLE
Write a test for an helper function 

### ISSUE THREAD

**Issue by opeolluwa** [opeolluwa/racoon#138]
[`set_jwt_exp()`](https://github.com/opeolluwa/racoon/blob/master/src/utils/jwt.rs#L154) is an utility function that accepts time in minutes as an argument and converts the parameter to milliseconds. 

It finally adds the converted parameter to the current UNIX epoch timestamp, and, finally return the summation. 

1. Move the [test(s) module](https://github.com/opeolluwa/racoon/blob/master/src/utils/jwt.rs#L54) available in the file to the base of the file.  
2. Write a test to validate the workings of the  `set_jwt_exp` function

**Comment by fvilers** [comment]
I'd like to fix this one.

**Comment by opeolluwa** [comment]
Yes please. 
I'd be glad to have you

**Comment by fvilers** [comment]
Thanks. While reading the [CONTRIBUTING](https://github.com/opeolluwa/racoon/blob/6cf8d9c4de7e7971554746f294dda894c8685d36/CONTRIBUTING.md#your-first-code-contribution) guide, I'm unsure if I should fork from the dev or the master branch. Which one should I use ?

**Comment by opeolluwa** [comment]
The dev branch please.

**Comment by opeolluwa** [comment]
My apologies @fvilers,  could you use the master branch instead so it will be easier to track changes

**Comment by opeolluwa** [comment]
Thank you so much for your time and the corrections too. 


Let's do this another time 

Cheers 🎉🦀
